export const moveTypes = {
  "Acid": "poison",
  "Air Slash": "flying",
  "Astonish": "ghost",
  "Aura Sphere": "fighting",
  "Avalanche": "ice",
  "Beak Blast": "flying",
  "Behemoth Bash": "steel",
  "Behemoth Blade": "steel",
  "Bite": "dark",
  "Brave Bird": "flying",
  "Brutal Swing": "dark",
  "Bubble": "water",
  "Bullet Punch": "steel",
  "Bullet Seed": "grass",
  "Counter": "fighting",
  "Crabhammer": "water",
  "Crush Grip": "normal",
  "Darkest Lariat": "dark",
  "Discharge": "electric",
  "Dragon Ascent": "flying",
  "Dragon Tail": "dragon",
  "Dynamic Punch": "fighting",
  "Earth Power": "ground",
  "Earthquake": "ground",
  "Fairy Wind": "fairy",
  "Fire Fang": "fire",
  "Fire Spin": "fire",
  "Fly": "flying",
  "Force Palm": "fighting",
  "Foul Play": "dark",
  "Freeze Shock": "ice",
  "Frenzy Plant": "grass",
  "Gigaton Hammer": "steel",
  "Grass Knot": "grass",
  "Gunk Shot": "poison",
  "Gust": "flying",
  "Hex": "ghost",
  "Hidden Power": "normal",
  "High Horsepower": "ground",
  "Hydro Cannon": "water",
  "Ice Burn": "ice",
  "Ice Fang": "ice",
  "Leaf Blade": "grass",
  "Leafage": "grass",
  "Lick": "ghost",
  "Low Kick": "fighting",
  "Magical Leaf": "grass",
  "Metal Claw": "steel",
  "Meteor Mash": "steel",
  "Moongeist Beam": "ghost",
  "Mud Shot": "ground",
  "Mud-Slap": "ground",
  "Origin Pulse": "water",
  "Overheat": "fire",
  "Peck": "flying",
  "Poison Jab": "poison",
  "Powder Snow": "ice",
  "Power Whip": "grass",
  "Precipice Blades": "ground",
  "Psycho Cut": "psychic",
  "Pyro Ball": "fire",
  "Razor Leaf": "grass",
  "Rock Slide": "rock",
  "Sacred Sword": "fighting",
  "Sandsear Storm": "ground",
  "Scorching Sands": "ground",
  "Secret Sword": "fighting",
  "Shadow Ball": "ghost",
  "Shadow Claw": "ghost",
  "Sky Attack": "flying",
  "Sludge Bomb": "poison",
  "Smack Down": "rock",
  "Snarl": "dark",
  "Steel Wing": "steel",
  "Sunsteel Strike": "steel",
  "Surf": "water",
  "Thunder Cage": "electric",
  "Thunder Shock": "electric",
  "Thunderbolt": "electric",
  "Vine Whip": "grass",
  "Volt Switch": "electric",
  "Water Gun": "water",
  "Water Shuriken": "water",
  "Waterfall": "water",
  "Wild Charge": "electric",
  "Wing Attack": "flying"
};
