export const scrapeTargets = {

    kyogre: {
        id: "kyogre",
        name: "Kyogre",
        tier: "5★ Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/382.png",
        imageAlt: "Official artwork of Kyogre",
        subtitle: "5★ Raid • April 8 to April 14",
        types: ["water"],
        weaknesses: "Grass, Electric",
        difficultyLabel: "Focus",
        difficulty: "Strong legendary raid, not built for solo play",
        bestUrl: "https://www.pokebattler.com/raids/defenders/KYOGRE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/KYOGRE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaAerodactyl: {
        id: "mega-aerodactyl",
        name: "Mega Aerodactyl",
        tier: "Mega Raid",
        themeClass: "rock-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10042.png",
        imageAlt: "Official artwork of Mega Aerodactyl",
        subtitle: "Mega Raid • April 8 to April 14",
        types: ["rock", "flying"],
        weaknesses: "Rock, Steel, Water, Electric, Ice",
        difficultyLabel: "Focus",
        difficulty: "Strong Steel, Water and Rock attackers",
        bestUrl: "https://www.pokebattler.com/raids/defenders/AERODACTYL_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/AERODACTYL_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    groudon: {
        id: "groudon",
        name: "Groudon",
        tier: "5★ Raid",
        themeClass: "ground-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png",
        imageAlt: "Official artwork of Groudon",
        subtitle: "5★ Raid • April 15 to April 21",
        types: ["ground"],
        weaknesses: "Water, Grass, Ice",
        difficultyLabel: "Focus",
        difficulty: "Legendary raid with strong offensive pressure",
        bestUrl: "https://www.pokebattler.com/raids/defenders/GROUDON/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/GROUDON/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaAlakazam: {
        id: "mega-alakazam",
        name: "Mega Alakazam",
        tier: "Mega Raid",
        themeClass: "psychic-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10037.png",
        imageAlt: "Official artwork of Mega Alakazam",
        subtitle: "Mega Raid • April 15 to April 21",
        types: ["psychic"],
        weaknesses: "Bug, Ghost, Dark",
        difficultyLabel: "Focus",
        difficulty: "Dark and Ghost attackers",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ALAKAZAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ALAKAZAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuKoko: {
        id: "tapu-koko",
        name: "Tapu Koko",
        tier: "5★ Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/785.png",
        imageAlt: "Official artwork of Tapu Koko",
        subtitle: "5★ Raid • April 22 to April 28",
        types: ["electric", "fairy"],
        weaknesses: "Poison, Ground",
        difficultyLabel: "Focus",
        difficulty: "Ground attackers are the most natural answer",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_KOKO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_KOKO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaSharpedo: {
        id: "mega-sharpedo",
        name: "Mega Sharpedo",
        tier: "Mega Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10070.png",
        imageAlt: "Official artwork of Mega Sharpedo",
        subtitle: "Mega Raid • April 22 to April 28",
        types: ["water", "dark"],
        weaknesses: "Fighting, Bug, Grass, Electric, Fairy",
        difficultyLabel: "Focus",
        difficulty: "Fighting attackers are especially strong",
        bestUrl: "https://www.pokebattler.com/raids/defenders/SHARPEDO_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/SHARPEDO_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuLele: {
        id: "tapu-lele",
        name: "Tapu Lele",
        tier: "5★ Raid",
        themeClass: "psychic-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/786.png",
        imageAlt: "Official artwork of Tapu Lele",
        subtitle: "5★ Raid • April 29 to May 5",
        types: ["psychic", "fairy"],
        weaknesses: "Poison, Ghost, Steel",
        difficultyLabel: "Focus",
        difficulty: "Steel and Ghost attackers work especially well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_LELE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_LELE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaBanette: {
        id: "mega-banette",
        name: "Mega Banette",
        tier: "Mega Raid",
        themeClass: "ghost-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10056.png",
        imageAlt: "Official artwork of Mega Banette",
        subtitle: "Mega Raid • April 29 to May 5",
        types: ["ghost"],
        weaknesses: "Ghost, Dark",
        difficultyLabel: "Focus",
        difficulty: "Dark attackers are very easy to build",
        bestUrl: "https://www.pokebattler.com/raids/defenders/BANETTE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/BANETTE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    nihilego: {
        id: "nihilego",
        name: "Nihilego",
        tier: "5★ Raid",
        themeClass: "rock-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/793.png",
        imageAlt: "Official artwork of Nihilego",
        subtitle: "5★ Raid • May 6 to May 12",
        types: ["rock", "poison"],
        weaknesses: "Ground, Psychic, Steel, Water",
        difficultyLabel: "Focus",
        difficulty: "Ground attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/NIHILEGO/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/NIHILEGO/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaCamerupt: {
        id: "mega-camerupt",
        name: "Mega Camerupt",
        tier: "Mega Raid",
        themeClass: "fire-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10087.png",
        imageAlt: "Official artwork of Mega Camerupt",
        subtitle: "Mega Raid • May 6 to May 12",
        types: ["fire", "ground"],
        weaknesses: "Water, Ground",
        difficultyLabel: "Focus",
        difficulty: "Use Water attackers due to double weakness.",
        bestUrl: "https://www.pokebattler.com/raids/defenders/CAMERUPT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/CAMERUPT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    buzzwole: {
        id: "buzzwole",
        name: "Buzzwole",
        tier: "5★ Raid",
        themeClass: "bug-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/794.png",
        imageAlt: "Official artwork of Buzzwole",
        subtitle: "Regional 5★ Raid • May 13 to May 19",
        types: ["bug", "fighting"],
        weaknesses: "Flying, Fire, Psychic, Fairy",
        difficultyLabel: "Regional",
        difficulty: "Flying attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/BUZZWOLE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/BUZZWOLE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    pheromosa: {
        id: "pheromosa",
        name: "Pheromosa",
        tier: "5★ Raid",
        themeClass: "bug-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/795.png",
        imageAlt: "Official artwork of Pheromosa",
        subtitle: "Regional 5★ Raid • May 13 to May 19",
        types: ["bug", "fighting"],
        weaknesses: "Flying, Fire, Psychic, Fairy",
        difficultyLabel: "Regional",
        difficulty: "Flying attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/PHEROMOSA/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/PHEROMOSA/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    xurkitree: {
        id: "xurkitree",
        name: "Xurkitree",
        tier: "5★ Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/796.png",
        imageAlt: "Official artwork of Xurkitree",
        subtitle: "Regional 5★ Raid • May 13 to May 19",
        types: ["electric"],
        weaknesses: "Ground",
        difficultyLabel: "Regional",
        difficulty: "Ground attackers completely dominate due to single weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/XURKITREE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/XURKITREE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaGlalie: {
        id: "mega-glalie",
        name: "Mega Glalie",
        tier: "Mega Raid",
        themeClass: "ice-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10074.png",
        imageAlt: "Official artwork of Mega Glalie",
        subtitle: "Mega Raid • May 13 to May 19",
        types: ["ice"],
        weaknesses: "Fighting, Rock, Steel, Fire",
        difficultyLabel: "Focus",
        difficulty: "Steel and Fighting attackers perform best overall",
        bestUrl: "https://www.pokebattler.com/raids/defenders/GLALIE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/GLALIE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuBulu: {
        id: "tapu-bulu",
        name: "Tapu Bulu",
        tier: "5★ Raid",
        themeClass: "grass-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/787.png",
        imageAlt: "Official artwork of Tapu Bulu",
        subtitle: "5★ Raid",
        types: ["grass", "fairy"],
        weaknesses: "Poison, Flying, Fire, Ice, Steel",
        difficultyLabel: "Standard",
        difficulty: "Poison attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_BULU/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_BULU/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaAltaria: {
        id: "mega-altaria",
        name: "Mega Altaria",
        tier: "Mega Raid",
        themeClass: "dragon-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10067.png",
        imageAlt: "Official artwork of Mega Altaria",
        subtitle: "Mega Raid",
        types: ["dragon", "fairy"],
        weaknesses: "Ice, Poison, Steel, Fairy",
        difficultyLabel: "Mega",
        difficulty: "Steel and Poison attackers are the safest general picks",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ALTARIA_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ALTARIA_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuFini: {
        id: "tapu-fini",
        name: "Tapu Fini",
        tier: "5★ Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/788.png",
        imageAlt: "Official artwork of Tapu Fini",
        subtitle: "5★ Raid",
        types: ["water", "fairy"],
        weaknesses: "Electric, Grass, Poison",
        difficultyLabel: "Standard",
        difficulty: "Electric, Grass, and Poison attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_FINI/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_FINI/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaMedicham: {
        id: "mega-medicham",
        name: "Mega Medicham",
        tier: "Mega Raid",
        themeClass: "psychic-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10054.png",
        imageAlt: "Official artwork of Mega Medicham",
        subtitle: "Mega Raid",
        types: ["fighting", "psychic"],
        weaknesses: "Flying, Ghost, Fairy",
        difficultyLabel: "Mega",
        difficulty: "Flying and Ghost attackers are strong",
        bestUrl: "https://www.pokebattler.com/raids/defenders/MEDICHAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/MEDICHAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    }
};