export const scrapeTargets = {

    kyogre: {
        id: "kyogre",
        name: "Kyogre",
        tier: "5★ Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/382.png",
        imageAlt: "Official artwork of Kyogre",
        subtitle: "5★ Raid • April 8 to April 14",
        types: ["water"],
        weaknesses: "Grass, Electric",
        difficultyLabel: "Focus",
        difficulty: "Strong legendary raid, not built for solo play",
        bestUrl: "https://www.pokebattler.com/raids/defenders/KYOGRE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/KYOGRE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaAerodactyl: {
        id: "mega-aerodactyl",
        name: "Mega Aerodactyl",
        tier: "Mega Raid",
        themeClass: "rock-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10042.png",
        imageAlt: "Official artwork of Mega Aerodactyl",
        subtitle: "Mega Raid • April 8 to April 14",
        types: ["rock", "flying"],
        weaknesses: "Rock, Steel, Water, Electric, Ice",
        difficultyLabel: "Focus",
        difficulty: "Strong Steel, Water and Rock attackers",
        bestUrl: "https://www.pokebattler.com/raids/defenders/AERODACTYL_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/AERODACTYL_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    groudon: {
        id: "groudon",
        name: "Groudon",
        tier: "5★ Raid",
        themeClass: "ground-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png",
        imageAlt: "Official artwork of Groudon",
        subtitle: "5★ Raid • April 15 to April 21",
        types: ["ground"],
        weaknesses: "Water, Grass, Ice",
        difficultyLabel: "Focus",
        difficulty: "Legendary raid with strong offensive pressure",
        bestUrl: "https://www.pokebattler.com/raids/defenders/GROUDON/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/GROUDON/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaAlakazam: {
        id: "mega-alakazam",
        name: "Mega Alakazam",
        tier: "Mega Raid",
        themeClass: "psychic-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10037.png",
        imageAlt: "Official artwork of Mega Alakazam",
        subtitle: "Mega Raid • April 15 to April 21",
        types: ["psychic"],
        weaknesses: "Bug, Ghost, Dark",
        difficultyLabel: "Focus",
        difficulty: "Dark and Ghost attackers",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ALAKAZAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ALAKAZAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuKoko: {
        id: "tapu-koko",
        name: "Tapu Koko",
        tier: "5★ Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/785.png",
        imageAlt: "Official artwork of Tapu Koko",
        subtitle: "5★ Raid • April 22 to April 28",
        types: ["electric", "fairy"],
        weaknesses: "Poison, Ground",
        difficultyLabel: "Focus",
        difficulty: "Ground attackers are the most natural answer",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_KOKO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_KOKO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaSharpedo: {
        id: "mega-sharpedo",
        name: "Mega Sharpedo",
        tier: "Mega Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10070.png",
        imageAlt: "Official artwork of Mega Sharpedo",
        subtitle: "Mega Raid • April 22 to April 28",
        types: ["water", "dark"],
        weaknesses: "Fighting, Bug, Grass, Electric, Fairy",
        difficultyLabel: "Focus",
        difficulty: "Fighting attackers are especially strong",
        bestUrl: "https://www.pokebattler.com/raids/defenders/SHARPEDO_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/SHARPEDO_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuLele: {
        id: "tapu-lele",
        name: "Tapu Lele",
        tier: "5★ Raid",
        themeClass: "psychic-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/786.png",
        imageAlt: "Official artwork of Tapu Lele",
        subtitle: "5★ Raid • April 29 to May 5",
        types: ["psychic", "fairy"],
        weaknesses: "Poison, Ghost, Steel",
        difficultyLabel: "Focus",
        difficulty: "Steel and Ghost attackers work especially well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_LELE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_LELE/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaBanette: {
        id: "mega-banette",
        name: "Mega Banette",
        tier: "Mega Raid",
        themeClass: "ghost-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10056.png",
        imageAlt: "Official artwork of Mega Banette",
        subtitle: "Mega Raid • April 29 to May 5",
        types: ["ghost"],
        weaknesses: "Ghost, Dark",
        difficultyLabel: "Focus",
        difficulty: "Dark attackers are very easy to build",
        bestUrl: "https://www.pokebattler.com/raids/defenders/BANETTE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/BANETTE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    nihilego: {
        id: "nihilego",
        name: "Nihilego",
        tier: "5★ Raid",
        themeClass: "rock-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/793.png",
        imageAlt: "Official artwork of Nihilego",
        subtitle: "5★ Raid • May 6 to May 12",
        types: ["rock", "poison"],
        weaknesses: "Ground, Psychic, Steel, Water",
        difficultyLabel: "Focus",
        difficulty: "Ground attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/NIHILEGO/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/NIHILEGO/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaCamerupt: {
        id: "mega-camerupt",
        name: "Mega Camerupt",
        tier: "Mega Raid",
        themeClass: "fire-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10087.png",
        imageAlt: "Official artwork of Mega Camerupt",
        subtitle: "Mega Raid • May 6 to May 12",
        types: ["fire", "ground"],
        weaknesses: "Water, Ground",
        difficultyLabel: "Focus",
        difficulty: "Use Water attackers due to double weakness.",
        bestUrl: "https://www.pokebattler.com/raids/defenders/CAMERUPT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/CAMERUPT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    buzzwole: {
        id: "buzzwole",
        name: "Buzzwole",
        tier: "5★ Raid",
        themeClass: "bug-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/794.png",
        imageAlt: "Official artwork of Buzzwole",
        subtitle: "Regional 5★ Raid • May 13 to May 19",
        types: ["bug", "fighting"],
        weaknesses: "Flying, Fire, Psychic, Fairy",
        difficultyLabel: "Standard",
        difficulty: "Flying attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/BUZZWOLE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/BUZZWOLE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    pheromosa: {
        id: "pheromosa",
        name: "Pheromosa",
        tier: "5★ Raid",
        themeClass: "bug-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/795.png",
        imageAlt: "Official artwork of Pheromosa",
        subtitle: "Regional 5★ Raid • May 13 to May 19",
        types: ["bug", "fighting"],
        weaknesses: "Flying, Fire, Psychic, Fairy",
        difficultyLabel: "Standard",
        difficulty: "Flying attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/PHEROMOSA/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/PHEROMOSA/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    xurkitree: {
        id: "xurkitree",
        name: "Xurkitree",
        tier: "5★ Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/796.png",
        imageAlt: "Official artwork of Xurkitree",
        subtitle: "Regional 5★ Raid • May 13 to May 19",
        types: ["electric"],
        weaknesses: "Ground",
        difficultyLabel: "Standard",
        difficulty: "Ground attackers completely dominate due to single weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/XURKITREE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/XURKITREE/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaGlalie: {
        id: "mega-glalie",
        name: "Mega Glalie",
        tier: "Mega Raid",
        themeClass: "ice-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10074.png",
        imageAlt: "Official artwork of Mega Glalie",
        subtitle: "Mega Raid • May 13 to May 19",
        types: ["ice"],
        weaknesses: "Fighting, Rock, Steel, Fire",
        difficultyLabel: "Focus",
        difficulty: "Steel and Fighting attackers perform best overall",
        bestUrl: "https://www.pokebattler.com/raids/defenders/GLALIE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/GLALIE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuBulu: {
        id: "tapu-bulu",
        name: "Tapu Bulu",
        tier: "5★ Raid",
        themeClass: "grass-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/787.png",
        imageAlt: "Official artwork of Tapu Bulu",
        subtitle: "5★ Raid",
        types: ["grass", "fairy"],
        weaknesses: "Poison, Flying, Fire, Ice, Steel",
        difficultyLabel: "Standard",
        difficulty: "Poison attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_BULU/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_BULU/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaAltaria: {
        id: "mega-altaria",
        name: "Mega Altaria",
        tier: "Mega Raid",
        themeClass: "dragon-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10067.png",
        imageAlt: "Official artwork of Mega Altaria",
        subtitle: "Mega Raid",
        types: ["dragon", "fairy"],
        weaknesses: "Ice, Poison, Steel, Fairy",
        difficultyLabel: "Mega",
        difficulty: "Steel and Poison attackers are the safest general picks",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ALTARIA_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ALTARIA_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tapuFini: {
        id: "tapu-fini",
        name: "Tapu Fini",
        tier: "5★ Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/788.png",
        imageAlt: "Official artwork of Tapu Fini",
        subtitle: "5★ Raid",
        types: ["water", "fairy"],
        weaknesses: "Electric, Grass, Poison",
        difficultyLabel: "Standard",
        difficulty: "Electric, Grass, and Poison attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TAPU_FINI/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TAPU_FINI/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaMedicham: {
        id: "mega-medicham",
        name: "Mega Medicham",
        tier: "Mega Raid",
        themeClass: "psychic-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10054.png",
        imageAlt: "Official artwork of Mega Medicham",
        subtitle: "Mega Raid",
        types: ["fighting", "psychic"],
        weaknesses: "Flying, Ghost, Fairy",
        difficultyLabel: "Mega",
        difficulty: "Flying and Ghost attackers are strong",
        bestUrl: "https://www.pokebattler.com/raids/defenders/MEDICHAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/MEDICHAM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    blacephalon: {
        id: "blacephalon",
        name: "Blacephalon",
        tier: "5★ Raid",
        themeClass: "ghost-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/806.png",
        imageAlt: "Official artwork of Blacephalon",
        subtitle: "5★ Raid • Jan 1 to Jan 5",
        types: ["fire", "ghost"],
        weaknesses: "Water, Rock, Ground, Ghost, Dark",
        difficultyLabel: "Standard",
        difficulty: "Dark and Ghost attackers perform best against Blacephalon",
        bestUrl: "https://www.pokebattler.com/raids/defenders/BLACEPHALON/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/BLACEPHALON/levels/RAID_LEVEL_ULTRA_BEAST/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    genesectBurn: {
        id: "genesect-burn",
        name: "Genesect (Burn Drive)",
        tier: "5★ Raid",
        themeClass: "steel-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/649.png",
        imageAlt: "Official artwork of Genesect (Burn Drive)",
        subtitle: "5★ Raid • Jan 5 to Jan 16",
        types: ["bug", "steel"],
        weaknesses: "Fire",
        difficultyLabel: "Focus",
        difficulty: "Fire attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/GENESECT_BURN_FORM/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/GENESECT_BURN_FORM/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    thundurusIncarnate: {
        id: "thundurus-incarnate",
        name: "Thundurus (Incarnate Forme)",
        tier: "5★ Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/642.png",
        imageAlt: "Official artwork of Thundurus (Incarnate Forme)",
        subtitle: "5★ Raid • Jan 16 to Jan 25",
        types: ["electric", "flying"],
        weaknesses: "Ice, Rock",
        difficultyLabel: "Standard",
        difficulty: "Ice and Rock attackers perform consistently well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/THUNDURUS/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/THUNDURUS/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    tornadusIncarnate: {
        id: "tornadus-incarnate",
        name: "Tornadus (Incarnate Forme)",
        tier: "5★ Raid",
        themeClass: "flying-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/641.png",
        imageAlt: "Official artwork of Tornadus (Incarnate Forme)",
        subtitle: "5★ Raid • Jan 25 to Feb 4",
        types: ["flying"],
        weaknesses: "Electric, Ice, Rock",
        difficultyLabel: "Standard",
        difficulty: "Electric, Ice, and Rock attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/TORNADUS/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/TORNADUS/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaSwampert: {
        id: "mega-swampert",
        name: "Mega Swampert",
        tier: "Mega Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10064.png",
        imageAlt: "Official artwork of Mega Swampert",
        subtitle: "Mega Raid Jan 1 to Jan 5",
        types: ["water", "ground"],
        weaknesses: "Grass",
        difficultyLabel: "Focus",
        difficulty: "Grass attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/SWAMPERT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/SWAMPERT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaBlaziken: {
        id: "mega-blaziken",
        name: "Mega Blaziken",
        tier: "Mega Raid",
        themeClass: "fire-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10050.png",
        imageAlt: "Official artwork of Mega Blaziken",
        subtitle: "Mega Raid • Jan 5 to Jan 16",
        types: ["fire", "fighting"],
        weaknesses: "Water, Flying, Ground, Psychic",
        difficultyLabel: "Standard",
        difficulty: "Water, Flying, Ground, and Psychic attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/BLAZIKEN_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/BLAZIKEN_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaSceptile: {
        id: "mega-sceptile",
        name: "Mega Sceptile",
        tier: "Mega Raid",
        themeClass: "grass-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10065.png",
        imageAlt: "Official artwork of Mega Sceptile",
        subtitle: "Mega Raid • Jan 16 to Jan 25",
        types: ["grass", "dragon"],
        weaknesses: "Ice, Fairy, Dragon, Flying, Poison, Bug",
        difficultyLabel: "Focus",
        difficulty: "Ice attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/SCEPTILE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/SCEPTILE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaAbsol: {
        id: "mega-absol",
        name: "Mega Absol",
        tier: "Mega Raid",
        themeClass: "dark-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10057.png",
        imageAlt: "Official artwork of Mega Absol",
        subtitle: "Mega Raid • Feb 21 to Mar 4",
        types: ["dark"],
        weaknesses: "Fighting, Fairy, Bug",
        difficultyLabel: "Easy",
        difficulty: "Fairy, Fighting, and Bug attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ABSOL_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ABSOL_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },
    megaAmpharos: {
        id: "mega-ampharos",
        name: "Mega Ampharos",
        tier: "Mega Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10045.png",
        imageAlt: "Official artwork of Mega Ampharos",
        subtitle: "Mega Raid • Jan 25 to Feb 4",
        types: ["electric", "dragon"],
        weaknesses: "Ground, Ice, Dragon, Fairy",
        difficultyLabel: "Standard",
        difficulty: "Ground, Ice, Dragon, and Fairy attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/AMPHAROS_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/AMPHAROS_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    dialga: {
        id: "dialga",
        name: "Dialga",
        tier: "5★ Raid",
        themeClass: "steel-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/483.png",
        imageAlt: "Official artwork of Dialga",
        subtitle: "5★ Raid • Feb 4 to Feb 16",
        types: ["steel", "dragon"],
        weaknesses: "Fighting, Ground",
        difficultyLabel: "Standard",
        difficulty: "Fighting and Ground attackers perform consistently well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/DIALGA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/DIALGA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    palkia: {
        id: "palkia",
        name: "Palkia",
        tier: "5★ Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/484.png",
        imageAlt: "Official artwork of Palkia",
        subtitle: "5★ Raid • Feb 4 to Feb 16",
        types: ["water", "dragon"],
        weaknesses: "Dragon, Fairy",
        difficultyLabel: "Standard",
        difficulty: "Dragon and Fairy attackers perform consistently well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/PALKIA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/PALKIA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaPidgeot: {
        id: "mega-pidgeot",
        name: "Mega Pidgeot",
        tier: "Mega Raid",
        themeClass: "flying-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10073.png",
        imageAlt: "Official artwork of Mega Pidgeot",
        subtitle: "Mega Raid • Feb 4 to Feb 16",
        types: ["normal", "flying"],
        weaknesses: "Rock, Electric, Ice",
        difficultyLabel: "Standard",
        difficulty: "Rock, Electric, and Ice attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/PIDGEOT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/PIDGEOT_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    solgaleo: {
        id: "solgaleo",
        name: "Solgaleo",
        tier: "5★ Raid",
        themeClass: "steel-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/791.png",
        imageAlt: "Official artwork of Solgaleo",
        subtitle: "5★ Raid • Feb 16 to Feb 21",
        types: ["psychic", "steel"],
        weaknesses: "Fire, Ground, Ghost, Dark",
        difficultyLabel: "Standard",
        difficulty: "Fire, Ground, Ghost, and Dark attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/SOLGALEO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/SOLGALEO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaSableye: {
        id: "mega-sableye",
        name: "Mega Sableye",
        tier: "Mega Raid",
        themeClass: "dark-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10066.png",
        imageAlt: "Official artwork of Mega Sableye",
        subtitle: "Mega Raid • Feb 16 to Feb 21",
        types: ["dark", "ghost"],
        weaknesses: "Fairy",
        difficultyLabel: "Focus",
        difficulty: "Fairy attackers are the only super-effective option",
        bestUrl: "https://www.pokebattler.com/raids/defenders/SABLEYE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/SABLEYE_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    lunala: {
        id: "lunala",
        name: "Lunala",
        tier: "5★ Raid",
        themeClass: "ghost-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/792.png",
        imageAlt: "Official artwork of Lunala",
        subtitle: "5★ Raid • Feb 21 to Mar 4",
        types: ["psychic", "ghost"],
        weaknesses: "Ghost, Dark",
        difficultyLabel: "Focus",
        difficulty: "Ghost and Dark attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/LUNALA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/LUNALA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    articuno: {
        id: "articuno",
        name: "Articuno",
        tier: "5★ Raid",
        themeClass: "ice-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png",
        imageAlt: "Official artwork of Articuno",
        subtitle: "5★ Raid • Mar 4 to Mar 10",
        types: ["ice", "flying"],
        weaknesses: "Rock, Fire, Electric, Steel",
        difficultyLabel: "Focus",
        difficulty: "Rock attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ARTICUNO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ARTICUNO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    zapdos: {
        id: "zapdos",
        name: "Zapdos",
        tier: "5★ Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png",
        imageAlt: "Official artwork of Zapdos",
        subtitle: "5★ Raid • Mar 4 to Mar 10",
        types: ["electric", "flying"],
        weaknesses: "Ice, Rock",
        difficultyLabel: "Standard",
        difficulty: "Ice and Rock attackers perform consistently well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ZAPDOS/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ZAPDOS/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    moltres: {
        id: "moltres",
        name: "Moltres",
        tier: "5★ Raid",
        themeClass: "fire-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png",
        imageAlt: "Official artwork of Moltres",
        subtitle: "5★ Raid • Mar 4 to Mar 10",
        types: ["fire", "flying"],
        weaknesses: "Rock, Water, Electric",
        difficultyLabel: "Focus",
        difficulty: "Rock attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/MOLTRES/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/MOLTRES/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaPinsir: {
        id: "mega-pinsir",
        name: "Mega Pinsir",
        tier: "Mega Raid",
        themeClass: "bug-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10040.png",
        imageAlt: "Official artwork of Mega Pinsir",
        subtitle: "Mega Raid • Mar 4 to Mar 10",
        types: ["bug", "flying"],
        weaknesses: "Rock, Fire, Electric, Ice, Flying",
        difficultyLabel: "Focus",
        difficulty: "Rock attackers dominate due to double weakness",
        bestUrl: "https://www.pokebattler.com/raids/defenders/PINSIR_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/PINSIR_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    zacian: {
        id: "zacian",
        name: "Zacian",
        tier: "5★ Raid",
        themeClass: "fairy-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/888.png",
        imageAlt: "Official artwork of Zacian",
        subtitle: "5★ Raid • Mar 11 to Mar 17",
        types: ["fairy"],
        weaknesses: "Poison, Steel",
        difficultyLabel: "Standard",
        difficulty: "Poison and Steel attackers perform consistently well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ZACIAN/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ZACIAN/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaSteelix: {
        id: "mega-steelix",
        name: "Mega Steelix",
        tier: "Mega Raid",
        themeClass: "steel-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10072.png",
        imageAlt: "Official artwork of Mega Steelix",
        subtitle: "Mega Raid • Mar 11 to Mar 17",
        types: ["steel", "ground"],
        weaknesses: "Fire, Water, Fighting, Ground",
        difficultyLabel: "Standard",
        difficulty: "Fire, Water, Fighting, and Ground attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/STEELIX_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/STEELIX_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    zamazenta: {
        id: "zamazenta",
        name: "Zamazenta",
        tier: "5★ Raid",
        themeClass: "fighting-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/889.png",
        imageAlt: "Official artwork of Zamazenta",
        subtitle: "5★ Raid • Mar 18 to Mar 24",
        types: ["fighting"],
        weaknesses: "Flying, Psychic, Fairy",
        difficultyLabel: "Standard",
        difficulty: "Flying, Psychic, and Fairy attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/ZAMAZENTA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/ZAMAZENTA/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaSlowbro: {
        id: "mega-slowbro",
        name: "Mega Slowbro",
        tier: "Mega Raid",
        themeClass: "water-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10071.png",
        imageAlt: "Official artwork of Mega Slowbro",
        subtitle: "Mega Raid • Mar 18 to Mar 24",
        types: ["water", "psychic"],
        weaknesses: "Electric, Grass, Bug, Ghost, Dark",
        difficultyLabel: "Standard",
        difficulty: "Electric, Grass, Ghost, and Dark attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/SLOWBRO_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/SLOWBRO_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    regieleki: {
        id: "regieleki",
        name: "Regieleki",
        tier: "5★ Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/894.png",
        imageAlt: "Official artwork of Regieleki",
        subtitle: "5★ Raid • Mar 25 to Mar 31",
        types: ["electric"],
        weaknesses: "Ground",
        difficultyLabel: "Focus",
        difficulty: "Ground attackers are the only super-effective option",
        bestUrl: "https://www.pokebattler.com/raids/defenders/REGIELEKI/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/REGIELEKI/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaHoundoom: {
        id: "mega-houndoom",
        name: "Mega Houndoom",
        tier: "Mega Raid",
        themeClass: "dark-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10048.png",
        imageAlt: "Official artwork of Mega Houndoom",
        subtitle: "Mega Raid • Mar 25 to Mar 31",
        types: ["dark", "fire"],
        weaknesses: "Water, Fighting, Ground, Rock",
        difficultyLabel: "Standard",
        difficulty: "Water, Fighting, Ground, and Rock attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/HOUNDOOM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/HOUNDOOM_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },
    regidrago: {
        id: "regidrago",
        name: "Regidrago",
        tier: "5★ Raid",
        themeClass: "dragon-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/895.png",
        imageAlt: "Official artwork of Regidrago",
        subtitle: "5★ Raid • Apr 1 to Apr 7",
        types: ["dragon"],
        weaknesses: "Ice, Dragon, Fairy",
        difficultyLabel: "Standard",
        difficulty: "Ice, Dragon, and Fairy attackers all perform well",
        bestUrl: "https://www.pokebattler.com/raids/defenders/REGIDRAGO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/REGIDRAGO/levels/RAID_LEVEL_5/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },

    megaManectric: {
        id: "mega-manectric",
        name: "Mega Manectric",
        tier: "Mega Raid",
        themeClass: "electric-theme",
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10055.png",
        imageAlt: "Official artwork of Mega Manectric",
        subtitle: "Mega Raid • Apr 1 to Apr 7",
        types: ["electric"],
        weaknesses: "Ground",
        difficultyLabel: "Focus",
        difficulty: "Ground attackers are the only super-effective option",
        bestUrl: "https://www.pokebattler.com/raids/defenders/MANECTRIC_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=true&includeShadow=true&includeMegas=true&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1",
        budgetUrl: "https://www.pokebattler.com/raids/defenders/MANECTRIC_MEGA/levels/RAID_LEVEL_MEGA/attackers/levels/40/strategies/CINEMATIC_ATTACK_WHEN_POSSIBLE/DEFENSE_RANDOM_MC?sort=ESTIMATOR&weatherCondition=NO_WEATHER&dodgeStrategy=DODGE_REACTION_TIME&aggregation=AVERAGE&includeLegendary=false&includeShadow=false&includeMegas=false&attackerTypes=POKEMON_TYPE_ALL&primalAssistants=&numParty=1"
    },
};

